Move the posins/postrm stuff from postins/postrm to kavlobs.postins and kvalobs.postrm.
git-svn-id: https://svn.met.no/kvoss/kvalobs/trunk@1726 422d51e2-5941-41ac-8e65-d5b5931239be

diff --git a/debian_files/kvalobs.postrm b/debian_files/kvalobs.postrm
--- a/debian_files/kvalobs.postrm
+++ b/debian_files/kvalobs.postrm
@@ -1,10 +1,126 @@
 #!/bin/sh
+# postrm script for kvalobs
+#
+# see: dh_installdeb(1)
 
 set -e
-#set -x
 
-if [ -f /usr/share/debconf/confmodule ]; then
-	. /usr/share/debconf/confmodule
-fi
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+. /usr/share/debconf/confmodule
+
+#BINDIR, BIN and DIR must be in sync with the respectives variables in postinst.
+
+BINDIR="/usr/bin"
+BIN="kv2kro kvDataInputd kvdataclt kvdbadmin 
+     kvManagerd kvmgrclt kvQabased kvServiced kvstart kvstop 
+     kvsynopdparse norcom2kv kvstart-postgres
+     kvstop-postgres"
+
+KVBINDIR="/usr/lib/kvalobs/bin"
+KVBIN="hirlam2kvalobs.sh
+       runbg
+       kvdbadmin.sh
+       lam2kv.cron
+       qabase_cron.sh
+       save_last_month.sh"
+
+
+ETC_FILES="kv_ctl.conf 
+           kvcron
+           pgclean-local.sql
+           save_last_month.conf
+           lam2kv/metdat.1h    
+           lam2kv/metdat.RR24         
+           lam2kv/posdat.PP    
+           lam2kv/pose.kvalobs
+           lam2kv/metdat.PP    
+           lam2kv/parameters.kvalobs  
+           lam2kv/posdat.RR12  
+           lam2kv/metdat.RR12  
+           lam2kv/parmap.kvalobs      
+           lam2kv/posdat.RR24  
+           lam2kv/stations.kvalobs
+           "
+
+
+DIRS="/usr/share/kvalobs 
+      /usr/share/kvalobs/db
+      /usr/share/kvalobs/kvsynop 
+      /usr/share/kvalobs/metadata 
+      /etc/kvalobs
+      /etc/kvalobs/lam2kv
+      /var/lib/kvalobs
+      /var/lib/kvalobs/norcom2kv
+      /var/lib/kvalobs/norcom2kv/data2kv
+      /var/lib/kvalobs/norcom2kv/tmp
+      /var/lib/kvalobs/lam2kv
+      /var/lib/kvalobs/lam2kv/log
+      /var/lib/kvalobs/lam2kv/upload
+      /var/lib/kvalobs/lam2kv/data
+      /var/log/kvalobs
+      /var/log/kvalobs/decoders
+      /var/log/kvalobs/decoders/SynopDecoder
+      /var/log/kvalobs/kvsynopdbadmin
+      /var/log/kvalobs/html
+      /var/run/kvalobs
+      /var/lib/kvalobs/service
+      /var/lib/kvalobs/service/subscribers"     
+
+
+case "$1" in
+    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
+
+  purge)
+    for i in $BIN; do
+        dpkg-statoverride --remove $BINDIR/$i
+     done
+
+    for i in $KVBIN; do
+        dpkg-statoverride --remove $KVBINDIR/$i
+     done
+
+     for i in $DIRS; do
+        dpkg-statoverride --remove $i
+     done
+
+     #Remove the cache databases.
+     for i in $SQLLITE_DB; do
+        dpkg-statoverride --remove $i
+        rm -f $i 
+     done
+     for i in $ETC_FILES; do
+	 dpkg-statoverride --remove /etc/kvalobs/$i
+     done
+     
+     #Delete my debconf entries in the database.
+     db_purge || true
+
+     update-rc.d kvalobs remove || true
+   
+     ;;
+   
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
